### ISSUE TITLE
Config doesn't work with module.exports syntax

### ISSUE THREAD

**Issue by ben-eb** [code42day/postcss-cli#17]
```
postcss -c ./postcss.js ./styles/main.css -o ./src/css/main.css
```

postcss.js:

``` js
module.exports = {
    "postcss-map" {
        basePath: './styles',
        maps: ['config.yml']
    },
    "cssnext": {
        compress: true
    }
};
```

stack:

```
/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/lib/parser.js:334
          throw Error('invalid json config file: ' + configPath)
                                                   ^
Error: invalid json config file: ./postcss.js
    at Error (native)
    at /Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/lib/parser.js:334:52
    at Array.forEach (native)
    at setConfig (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/lib/parser.js:319:32)
    at module.exports (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/lib/parser.js:219:3)
    at parseArgs (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/index.js:403:18)
    at Object.Argv.self.showHelp (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/index.js:300:23)
    at Object.self.fail (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/lib/usage.js:36:33)
    at Object.Argv.Object.defineProperty.get [as argv] (/Users/bbriggs/projects/test/node_modules/postcss-cli/node_modules/yargs/index.js:394:15)
    at Object.<anonymous> (/Users/bbriggs/projects/test/node_modules/postcss-cli/index.js:40:3)
```

**Comment by ben-eb** [comment]
I have a syntax error. :sleepy:

```
postcss -u cssnext -u postcss-map -c ./postcss.js ./styles/main.css -o ./src/css/main.css
```
